//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mAsistenciaContainer : DbContext
    {
        public mAsistenciaContainer()
            : base("name=mAsistenciaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Trabajador> TrabajadorSet { get; set; }
        public virtual DbSet<Oficina> OficinaSet { get; set; }
        public virtual DbSet<Asistencia> AsistenciaSet { get; set; }
        public virtual DbSet<Local> LocalSet { get; set; }
        public virtual DbSet<Horario> HorarioSet { get; set; }
        public virtual DbSet<HorarioDia> HorarioDiaSet { get; set; }
        public virtual DbSet<HorarioSemana> HorarioSemanaSet { get; set; }
        public virtual DbSet<ReglasTardanza> ReglasTardanzaSet { get; set; }
        public virtual DbSet<PermisosHoras> PermisosHorasSet { get; set; }
        public virtual DbSet<TipoPermisos> TipoPermisosSet { get; set; }
        public virtual DbSet<PermisosDias> PermisosDiasSet { get; set; }
        public virtual DbSet<DiaFestivo> DiaFestivoSet { get; set; }
        public virtual DbSet<CronogramaVacaciones> CronogramaVacacionesSet { get; set; }
        public virtual DbSet<Empresa> EmpresaSet { get; set; }
    }
}
