//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horario()
        {
            this.HorarioDia = new HashSet<HorarioDia>();
        }
    
        public int Id { get; set; }
        public System.DateTime Entrada { get; set; }
        public System.DateTime Salida { get; set; }
        public string Nombre { get; set; }
        public System.DateTime TiempoTardanza { get; set; }
        public System.DateTime FinPicadoEntrada { get; set; }
        public System.DateTime FinPicadoSalida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioDia> HorarioDia { get; set; }
    }
}
