//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosDias
    {
        public int Id { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
        public virtual TipoPermisos TipoPermisos { get; set; }
    }
}
