//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPermisos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Computable { get; set; }
    
        public virtual PermisosHoras PermisosHoras { get; set; }
        public virtual PermisosDias PermisosDias { get; set; }
    }
}
